name: GitHub Actions
run-name: Testing code 🚀
on: [push]
jobs:
  Python-format:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: python3 --version
      - run: python3 -m venv venv
      - name: Format python files
        run: |
          . venv/bin/activate
          pip install -r requirements_dev.txt
          make black-check
          deactivate
      - run: echo "🍏 This job's status is ${{ job.status }}."

  Python-lint:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: python3 --version
      - run: python3 -m venv venv
      - name: Lint python files
        run: |
          . venv/bin/activate
          pip install -r requirements_dev.txt
          make pyflakes
          deactivate
      - run: echo "🍏 This job's status is ${{ job.status }}."

  Google-Colaboratory-notebook-diff:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: python3 --version
      - run: python3 -m venv venv
      - name: Diff notebook
        run: |
          . venv/bin/activate
          pip install -r requirements_dev.txt
          make notebook-check
          deactivate
      - run: echo "🍏 This job's status is ${{ job.status }}."
